[package]
name    = "domain"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
uuid      = { workspace = true }
thiserror = { workspace = true }
log       = { workspace = true }
tokio     = { workspace = true }
